name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pyxem
  - hyperspy
  - diffsims
  - ipywidgets
  - lmfit
  - orix
  - numba >= 0.56.0
  - dask
  - scikit-image
  - scikit-learn
  - scipy
  - transforms3d
